services:
  app:
    image: ${WRITEFREELY_IMAGE:-ghcr.io/owner/repo:latest}
    container_name: ${WRITEFREELY_APP_CONTAINER:-writefreely}
    volumes:
      - ${WRITEFREELY_DATA_DIR:-./data}:/data
      - ${WRITEFREELY_PROD_CONFIG:-./config.docker.ini}:/go/config.ini:ro
      - ${WRITEFREELY_KEYS_DIR:-./keys}:/go/keys
    ports:
      - 127.0.0.1:${WRITEFREELY_PORT:-8080}:8080
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: ${MARIADB_IMAGE:-mariadb:latest}
    container_name: ${WRITEFREELY_DB_CONTAINER:-writefreely-mariadb}
    volumes:
      - ${WRITEFREELY_DB_DIR:-./db}:/var/lib/mysql
    environment:
      - TZ=${TZ:-Etc/UTC}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-writefreely}
      - MYSQL_USER=${MYSQL_USER:-writefreely}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: unless-stopped
